[project]
name = "transformers-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.1",
    "ipykernel>=6.30.1",
    "nbdev>=2.4.5",
    "notebook>=7.4.5",
    "numpy>=2.3.2",
]
